// === Layouts ===
export { default as AdminLayout } from './layouts/AdminLayout'
export { default as DashboardLayout } from './layouts/DashboardLayout'
export { default as MySpace } from './layouts/MySpace'
export { default as StudentLayout } from './layouts/StudentLayout'
export { default as TeacherLayout } from './layouts/TeacherLayout'

// === Teacher Components (used by Teacher pages) ===
export { default as AddExam } from './Teacher/Exam/AddExam'
export { default as CreateExamWizard } from './Teacher/Exam/CreateExam'
export { default as EditExamMetadataModal } from './Teacher/Exam/EditExamMetadataModal'
export { default as ExamCard } from './Teacher/Exam/ExamCard'
export { default as ExamDropdown } from './Teacher/Exam/ExamDropdown'
export { default as ExamPreview } from './Teacher/Exam/ExamPreview'
export { default as ExamHeading } from './Teacher/Exam/Heading'
export { default as AddMultiQuestion } from './Teacher/ExamQuestion/AddMultiQuestion'
export { default as AddQuestionToExamModal } from './Teacher/ExamQuestion/AddQuestionToExamModal'
export { default as DropdownExamQuestion } from './Teacher/ExamQuestion/DropdownCard'
export { default as EditExamQuestionModal } from './Teacher/ExamQuestion/EditExamQuestionModal'
export { default as ExamQuestionPreviewModal } from './Teacher/ExamQuestion/ExamQuestionPreviewModal'
export { default as ExamQuestionHeading } from './Teacher/ExamQuestion/Heading'
export { default as ExamQuestionCard } from './Teacher/ExamQuestion/QuestionCard'
export { default as QuestionDisplayCard } from './Teacher/ExamQuestion/QuestionCard/QuestionDisplayCard'
export { default as AddQuestion } from './Teacher/Question/AddQuestion'
export { default as BlockBuilder } from './Teacher/Question/BlockBuilder'
export { default as EditBlockFullModal } from './Teacher/Question/EditBlockFullModal'
export { default as EditBlockModal } from './Teacher/Question/EditBlockModal'
export { default as QuestionHeading } from './Teacher/Question/Heading'
export { default as ImportQuestion } from './Teacher/Question/ImportQuestion'
export { default as QuestionCard } from './Teacher/Question/QuestionCard'
export { default as QuestionDetailModal } from './Teacher/Question/QuestionDetailModal'